/*
 * File: app/view/FormPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TasksListDemo.view.FormPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.formpanel',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Button',
        'Ext.field.Toggle'
    ],

    config: {
        items: [
            {
                xtype: 'fieldset',
                itemId: 'taskFormField',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Email',
                        labelWidth: '35%',
                        name: 'email',
                        required: true
                    },
                    {
                        xtype: 'passwordfield',
                        label: 'Password',
                        labelWidth: '35%',
                        name: 'password',
                        required: true
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'saveButton',
                margin: 10,
                ui: 'action',
                text: 'Login'
            }
        ]
    }

});