/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TasksListDemo.view.MainView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.mainview',

    requires: [
        'TasksListDemo.view.TaskList',
        'Ext.navigation.Bar',
        'Ext.Button',
        'Ext.dataview.List'
    ],

    config: {
        itemId: 'mainView',
        navigationBar: {
            docked: 'top',
            itemId: 'navBar',
            items: [
                {
                    xtype: 'button',
                    align: 'right',
                    itemId: 'addButton',
                    iconCls: '',
                    text : 'Login'
                },
                {
                    xtype: 'button',
                    align: 'right',
                    itemId: 'addButton1',
                    iconCls: '',
                    hidden:true,
                    text : 'Logout'
                }
            ]
        },
        items: [
            {
                xtype: 'tasklist'
            }
            // ,
            // {
            //     xtype: 'panel',
            //     //html: '<img src="http://src.sencha.io/https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=Example" alt="My smaller"/>'
            //     html : '<img style="height: 300px; width: 320px;" src="https://api.qrserver.com/v1/create-qr-code/?size=100x100&data=PrashantYadav" />'
            // }
        ]
    }

});