/*
 * File: app/store/Tasks.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TasksListDemo.store.Tasks', {
    extend: 'Ext.data.Store',

    requires: [
        'TasksListDemo.model.Task',
    ],

    config: {
        data: [
            {

                email: '<img style="height: 300px; width: 320px;" src="https://lh4.googleusercontent.com/zrHvi1lFxBtlb7O_RUWA4_JQwyrMIdOQLyFfJUSBsxC49ftZytMXzjWkNwy0z6hz8xf3DNeeTKY=w2512-h1006">',
               
            }
        ],
        model: 'TasksListDemo.model.Task',
        storeId: 'Tasks'
    }
});